name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file AvalonApiNoDB.Api/Dockerfile --tag avalon-api:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'couchavalon'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'avalon-api:${{ github.sha }}'
